const express = require('express');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(express.static(path.join(__dirname, 'public')));
app.get('/health', (req, res) => res.json({ status: 'ok', version: '7.3.0' }));
app.get('/api/config', (req, res) => res.json({ backendUrl: 'https://all-arab-services.onrender.com', firebase: { apiKey: process.env.FIREBASE_API_KEY || 'AIzaSyBm-ZwOv8oPd_0rms_2oesGz3fDmt5ogvA', projectId: process.env.FIREBASE_PROJECT_ID || 'all-arab-services-750ad', databaseUrl: process.env.FIREBASE_DATABASE_URL || 'https://all-arab-services-750ad-default-rtdb.europe-west1.firebasedatabase.app' }, studioUrl: '/index.html', version: '7.3.0' }));
app.get('/api/version', (req, res) => res.json({ version: '7.3.0', modular: true }));
app.get('/api/ads', (req, res) => res.json({ enabled: true, defaultPlatform: 'custom_json' }));
app.get('/api/identity', (req, res) => res.json({ appName: 'App Engine Studio' }));
app.post('/api/stats', (req, res) => res.json({ status: 'ok' }));
app.get('/api/stats', (req, res) => res.json({ installs: 0 }));
app.post('/api/admin/commands', (req, res) => res.json({ status: 'queued' }));
app.listen(PORT, () => console.log('Backend v7.3.0 on port ' + PORT));
