"""
SECTION 12 — PROPOSED MAIN FUNCTION KEYS

Registers the canonical function-key namespace from Section 12.
Every key has: key, title, description, inputs, outputs, dependencies,
failure_modes, recovery_actions, evolution_hooks, section.
"""
from __future__ import annotations

from typing import Any, Dict, List


# All keys from Sections 12.1 through 12.13
CANONICAL_KEYS: List[str] = [
    # 12.1 Core
    "core.state_manager", "core.virtual_file_system", "core.schema_validator",
    "core.event_bus", "core.logger", "core.toast_adapter", "core.history_manager",
    "core.snapshot_manager", "core.rollback_manager", "core.config_loader",
    "core.config_writer", "core.package_sanitizer", "core.xml_escaper",
    "core.java_escaper", "core.kotlin_escaper", "core.gradle_escaper",
    "core.json_escaper", "core.color_normalizer", "core.list_deduper",
    "core.path_normalizer", "core.id_normalizer", "core.name_normalizer",
    # 12.2 Ingestion
    "ingest.javascript_parser", "ingest.java_parser", "ingest.kotlin_parser",
    "ingest.dart_parser", "ingest.xml_parser", "ingest.gradle_parser",
    "ingest.json_parser", "ingest.yaml_parser", "ingest.zip_reader",
    "ingest.github_connector", "ingest.cloud_connector", "ingest.termux_fs_connector",
    "ingest.linux_fs_connector", "ingest.no_code_connector", "ingest.ai_spec_connector",
    # 12.3 Audit
    "audit.line_by_line_reviewer", "audit.syntax_checker", "audit.template_checker",
    "audit.xml_checker", "audit.gradle_checker", "audit.manifest_checker",
    "audit.resource_checker", "audit.dependency_checker", "audit.path_checker",
    "audit.security_checker", "audit.privacy_checker", "audit.performance_checker",
    "audit.maintainability_checker",
    # 12.4 Repair
    "repair.patch_generator", "repair.template_fixer", "repair.escape_fixer",
    "repair.path_fixer", "repair.xml_fixer", "repair.gradle_fixer",
    "repair.manifest_fixer", "repair.resource_fixer", "repair.dependency_fixer",
    "repair.validator_fixer", "repair.zip_fixer", "repair.export_fixer",
    # 12.5 Generator
    "generator.orchestrator", "generator.profile_selector",
    "generator.app_identity_builder", "generator.build_profile_builder",
    "generator.language_profile_builder", "generator.theme_profile_builder",
    "generator.permission_profile_builder", "generator.dependency_profile_builder",
    "generator.screen_graph_builder", "generator.navigation_graph_builder",
    "generator.component_registry_builder", "generator.resource_registry_builder",
    "generator.asset_registry_builder", "generator.service_registry_builder",
    "generator.receiver_registry_builder", "generator.provider_registry_builder",
    # 12.6 Android
    "android.gradle_settings_builder", "android.gradle_root_builder",
    "android.gradle_properties_builder", "android.gradle_app_builder",
    "android.gradle_dependency_resolver", "android.gradle_proguard_builder",
    "android.gradle_wrapper_builder", "android.manifest_builder",
    "android.colors_builder", "android.strings_builder", "android.dimens_builder",
    "android.arrays_builder", "android.styles_builder", "android.themes_builder",
    "android.network_security_builder", "android.file_paths_builder",
    "android.layout_builder", "android.layout_webview", "android.layout_recycler",
    "android.layout_listview", "android.layout_default", "android.layout_fragment",
    "android.layout_item_builder", "android.activity_builder",
    "android.activity_java_builder", "android.activity_kotlin_builder",
    "android.activity_webview_builder", "android.activity_recycler_builder",
    "android.activity_listview_builder", "android.activity_default_builder",
    "android.fragment_builder", "android.service_builder_optional",
    "android.receiver_builder_optional", "android.provider_builder_optional",
    "android.asset_builder", "android.permission_builder",
    "android.signing_config_builder_optional",
    # 12.7 Multi-platform
    "flutter.pubspec_builder_optional", "flutter.main_dart_builder_optional",
    "flutter.theme_builder_optional", "flutter.android_manifest_adapter_optional",
    "react_native.package_json_builder_optional",
    "react_native.app_tsx_builder_optional",
    "ndk.cmake_builder_optional", "ndk.cpp_bridge_builder_optional",
    # 12.8 Firebase / Cloud
    "firebase.config_builder", "firebase.rules_builder", "firebase.admins_builder",
    "firebase.database_builder_optional", "firebase.firestore_builder_optional",
    "firebase.storage_builder_optional", "firebase.auth_builder_optional",
    "firebase.remote_config_builder_optional",
    "cloud.env_builder_optional", "cloud.secret_manager_advisor_optional",
    "cloud.storage_adapter_optional", "cloud.functions_adapter_optional",
    # 12.9 Validator
    "validator.static_rules", "validator.xml_validator", "validator.json_validator",
    "validator.yaml_validator", "validator.gradle_validator",
    "validator.manifest_validator", "validator.resource_validator",
    "validator.dependency_validator", "validator.permission_validator",
    "validator.privacy_validator", "validator.governance_validator",
    "validator.export_validator", "validator.zip_validator",
    "validator.build_script_validator", "validator.ci_validator",
    # 12.10 Export
    "export.orchestrator", "export.download_adapter", "export.zip_writer",
    "export.zip_compressor_optional", "export.json_exporter", "export.yaml_exporter",
    "export.xml_exporter", "export.csv_exporter", "export.markdown_exporter",
    "export.html_preview_exporter", "export.patch_exporter", "export.diff_exporter",
    "export.ast_exporter_optional", "export.diagram_exporter",
    "export.test_suite_exporter", "export.ci_workflow_exporter",
    "export.docs_exporter", "export.admin_bundle_exporter",
    "export.governance_bundle_exporter",
    # 12.11 Governance
    "governance.event_bus", "governance.button_press_processor",
    "governance.usage_meter", "governance.session_timer",
    "governance.identity_resolver", "governance.device_identity_provider",
    "governance.account_identity_provider", "governance.consent_manager",
    "governance.policy_engine", "governance.rbac_engine",
    "governance.entitlement_engine", "governance.action_gate",
    "governance.notification_trigger", "governance.warning_trigger",
    "governance.ad_trigger", "governance.audit_logger",
    "governance.remote_config_sync", "governance.feature_flag_engine",
    "governance.kill_switch", "governance.privacy_guard",
    # 12.12 Self-healing / Evolution
    "self_healing.error_classifier", "self_healing.retry_manager",
    "self_healing.fallback_manager", "self_healing.snapshot_manager",
    "self_healing.rollback_manager", "self_healing.safe_mode_manager",
    "self_healing.patch_queue", "self_healing.recovery_reporter",
    "evolution.plugin_loader", "evolution.schema_migrator",
    "evolution.feature_flag_loader", "evolution.template_migrator",
    "evolution.module_upgrader", "evolution.compatibility_guard",
    # 12.13 Supervisor
    "supervisor.auth_provider", "supervisor.role_manager",
    "supervisor.permission_manager", "supervisor.silent_editor",
    "supervisor.edit_validator", "supervisor.edit_previewer",
    "supervisor.edit_committer", "supervisor.edit_rollback",
    "supervisor.audit_viewer", "supervisor.policy_editor",
    "supervisor.feature_flag_editor", "supervisor.user_entitlement_editor",
    "supervisor.device_entitlement_editor", "supervisor.ad_policy_editor",
    "supervisor.notification_policy_editor", "supervisor.privacy_policy_editor",
    # 16A HTML Engine Studio + Universal DB
    "html.dom_sanitizer", "html.safe_renderer",
    "preview.phone_renderer", "preview.json_renderer",
    "preview.console_renderer", "preview.screen_renderer",
    "preview.theme_renderer", "preview.ad_renderer",
    "preview.unified_renderer", "preview.html_sandbox", "preview.state_simulator",
    "engine.screen_builder", "engine.field_builder", "engine.action_builder",
    "engine.component_registry", "engine.visibility_engine",
    "engine.validation_engine", "engine.navigation_engine",
    "engine.data_binding_engine", "engine.database_binding_engine",
    "engine.telemetry_hook", "engine.consent_hook",
    "engine.permission_hook", "engine.feature_flag_hook",
    "kotlin.engine_runtime", "kotlin.config_loader",
    "kotlin.remote_config_loader", "kotlin.local_fallback_loader",
    "kotlin.theme_manager", "kotlin.style_applier",
    "kotlin.screen_renderer", "kotlin.field_renderer",
    "kotlin.action_dispatcher", "kotlin.component_registry",
    "kotlin.visibility_engine", "kotlin.permission_checker",
    "kotlin.feature_flag_checker", "kotlin.consent_manager",
    "kotlin.usage_meter", "kotlin.audit_logger",
    "kotlin.database_provider_factory", "kotlin.repository_layer",
    "kotlin.offline_queue", "kotlin.sync_engine",
    "kotlin.firebase_identity_manager", "kotlin.ad_manager",
    "kotlin.unified_renderer", "kotlin.admin_manager",
    "kotlin.notification_manager", "kotlin.navigation_manager",
    "kotlin.error_recovery_manager",
    "firebase.rules_builder", "firebase.admins_builder",
    "firebase.feature_flags_builder", "firebase.permission_matrix_builder",
    "firebase.render_settings_builder", "firebase.theme_config_builder",
    "firebase.ad_config_builder", "firebase.identity_config_builder",
    "firebase.audit_log_builder", "firebase.seed_metadata_builder",
    "firebase.security_validator",
    "admin.button_manager", "admin.notification_sender", "admin.coupon_manager",
    "admin.json_builder", "admin.db_uploader", "admin.render_config_editor",
    "admin.responses_viewer", "admin.audit_logs_viewer", "admin.user_roles_manager",
    "admin.system_health_monitor", "admin.database_seed_manager",
    "admin.database_migration_manager", "admin.offline_sync_manager",
    "admin.identity_config_manager", "admin.ads_config_manager",
    "admin.theme_config_manager", "admin.feature_flag_manager",
    "admin.permission_matrix_manager", "admin.backup_manager", "admin.restore_manager",
    "renderer.unified_renderer", "renderer.field_order_engine",
    "renderer.mandatory_field_engine", "renderer.text_exporter",
    "renderer.json_exporter", "renderer.csv_exporter",
    "renderer.html_preview", "renderer.markdown_exporter_optional",
    "renderer.database_record_mapper",
    "theme.color_tokens", "theme.typography", "theme.spacing",
    "theme.borders", "theme.shadows", "theme.animations", "theme.gradients",
    "theme.components", "theme.screen_layouts", "theme.dark_mode",
    "theme.rtl_support", "theme.contrast_checker", "theme.validator",
    "theme.exporter", "theme.remote_loader", "theme.local_fallback",
    "ads.global_config", "ads.banner_controller", "ads.interstitial_controller",
    "ads.rewarded_controller", "ads.native_controller", "ads.app_open_controller",
    "ads.dynamic_json_controller", "ads.admob_adapter", "ads.facebook_adapter",
    "ads.unity_adapter", "ads.custom_json_adapter", "ads.frequency_capper",
    "ads.cooldown_manager", "ads.consent_gate", "ads.event_logger",
    "ads.preview_renderer", "ads.config_validator",
    "identity.virtual_fields", "identity.real_fields",
    "identity.firebase_credentials", "identity.ad_identity",
    "identity.support_identity", "identity.localization_identity",
    "identity.branding_identity", "identity.validator",
    "identity.remote_switcher", "identity.fallback_manager",
    "identity.audit_logger", "identity.dry_run_preview", "identity.rollback_manager",
    "html_io.parser", "html_io.html_to_zip", "html_io.html_to_json",
    "html_io.json_to_html", "html_io.asset_extractor", "html_io.css_extractor",
    "html_io.js_extractor", "html_io.metadata_extractor",
    "html_io.manifest_builder", "html_io.preview_sandbox",
    "html_io.validator", "html_io.path_normalizer",
    "templates.registry", "templates.search_engine", "templates.filter_engine",
    "templates.importer", "templates.validator", "templates.preview_renderer",
    "templates.zip_exporter", "templates.bulk_exporter",
    "templates.seed_importer", "templates.version_manager",
    "json_tools.validator", "json_tools.schema_generator",
    "json_tools.diff_viewer", "json_tools.merger",
    "json_tools.formatter", "json_tools.minifier",
    "json_tools.path_finder_optional", "json_tools.csv_converter_optional",
    "json_tools.kotlin_generator_optional", "json_tools.java_generator_optional",
    "json_tools.dart_generator_optional", "json_tools.xml_converter_optional",
    "json_tools.yaml_converter_optional",
    "db.provider_factory", "db.interface_contract", "db.mock_provider",
    "db.local_provider", "db.remote_provider", "db.schema_manager",
    "db.seed_manager", "db.migration_manager", "db.repository",
    "db.query_builder", "db.transaction_manager", "db.batch_manager",
    "db.subscription_manager", "db.offline_queue", "db.sync_engine",
    "db.cache_manager", "db.backup_manager", "db.restore_manager",
    "db.validation_manager", "db.audit_logger",
    "html_state.autosave", "html_state.manual_save", "html_state.import_manager",
    "html_state.export_manager", "html_state.clear_manager",
    "html_state.undo_manager", "html_state.redo_manager_optional",
    "html_state.snapshot_manager", "html_state.recovery_manager",
    "html_state.storage_quota_manager",
    "export.unified_bundle_builder", "export.asset_injector",
    "export.firebase_injector", "export.kotlin_config_injector",
    "export.database_seed_injector", "export.template_bundle_builder",
    "export.admin_bundle_builder", "export.test_fixture_builder",
    "export.validation_gate", "export.rollback_gate",
    "tests.html_ui_tests", "tests.html_state_tests", "tests.html_security_tests",
    "tests.engine_tests", "tests.theme_tests", "tests.ads_tests",
    "tests.identity_tests", "tests.html_io_tests", "tests.templates_tests",
    "tests.json_tools_tests", "tests.admin_tests",
    "tests.db_mock_tests", "tests.db_local_tests", "tests.db_remote_tests",
    "tests.db_sync_tests", "tests.db_migration_tests", "tests.db_security_tests",
    "tests.governance_tests",
]


class FunctionKeys:
    def __init__(self, ctx):
        self.ctx = ctx

    def run(self) -> None:
        # Register every canonical key if not already registered
        for key in CANONICAL_KEYS:
            if key not in self.ctx.module_registry:
                self.ctx.module_registry[key] = {
                    "key": key,
                    "title": key.split(".")[-1].replace("_", " ").title(),
                    "description": f"Canonical function key from Section 12: {key}",
                    "section": 12,
                    "inputs": [], "outputs": [], "dependencies": [],
                    "failureModes": [], "recoveryActions": [], "evolutionHooks": [],
                }

        self.ctx.audit_log.append({
            "section": 12,
            "status": "ok",
            "canonical_keys_total": len(CANONICAL_KEYS),
            "registry_size": len(self.ctx.module_registry),
            "message": f"Function key registry: {len(CANONICAL_KEYS)} canonical keys registered",
        })
