"""
templates/generate_templates.py — Generate 100 Android app templates.

Each template is a JSON file with:
    {
        "name": "Calculator",
        "package": "app.bardom.calc",
        "description": "A simple calculator app",
        "features": [
            "Add two numbers",
            "Subtract two numbers",
            ...
        ]
    }

The self_test runner picks up every template_*.json under templates/ and
runs the full generate -> build pipeline on each.
"""
from __future__ import annotations

import json
from pathlib import Path

TEMPLATES = [
    # 1-10: utility apps
    ("Calculator", "app.bardom.calc",
     "A simple calculator with basic arithmetic operations",
     ["Display numeric keypad 0-9", "Add two numbers", "Subtract two numbers",
      "Multiply two numbers", "Divide two numbers with divide-by-zero guard",
      "Clear button to reset display", "Backspace button to delete last digit",
      "Decimal point support", "Percentage calculation", "Memory store/recall"]),
    ("Notes", "app.bardom.notes",
     "A lightweight note-taking app",
     ["Create a new note", "Edit existing note", "Delete a note with confirmation",
      "List all notes by date", "Search notes by keyword",
      "Pin important notes to top", "Export note as text file",
      "Dark mode toggle", "Auto-save on edit", "Share note via system share"]),
    ("Todo List", "app.bardom.todo",
     "A todo list with reminders",
     ["Add a todo item", "Mark item as completed", "Delete a todo item",
      "Edit an existing item", "Set due date", "Set priority high/medium/low",
      "Filter by status", "Sort by date or priority",
      "Notification before due date", "Statistics: total/done/pending"]),
    ("Flashlight", "app.bardom.flashlight",
     "Turn the camera flash on/off as a flashlight",
     ["Toggle flashlight on/off", "Auto-off after 5 minutes",
      "SOS morse code mode", "Strobe light mode with adjustable speed",
      "Widget for home screen", "Battery level indicator",
      "Keep screen on while active", "Vibrate on toggle",
      "Launch from lock screen", "Save last brightness"]),
    ("Compass", "app.bardom.compass",
     "A magnetic compass using device sensors",
     ["Show north direction", "Display heading in degrees",
      "Switch between true north and magnetic north",
      "Vibrate when facing north", "Night mode with red text",
      "Lock current heading", "Show latitude/longitude from GPS",
      "Calibration helper", "Background color change by direction",
      "Save favorite directions"]),
    ("Stopwatch", "app.bardom.stopwatch",
     "A precise stopwatch with lap times",
     ["Start/pause stopwatch", "Reset to zero",
      "Record lap times", "Display lap difference",
      "Save session history", "Export times as CSV",
      "Continue in background", "Voice announcement every minute",
      "Large digits display", "Haptic feedback on lap"]),
    ("Timer", "app.bardom.timer",
     "A countdown timer with multiple presets",
     ["Set custom duration", "Start/pause timer",
      "Preset 1/3/5/10 minute buttons", "Notification when finished",
      "Sound alarm", "Vibrate alarm", "Continue in background",
      "Add 1 minute extension", "Multiple parallel timers",
      "Save recent timers"]),
    ("QR Code Generator", "app.bardom.qrgen",
     "Generate QR codes from text",
     ["Input text or URL", "Generate QR code image",
      "Save QR to gallery", "Share QR image",
      "Adjust QR size", "Adjust QR color",
      "Generate from clipboard", "Generate from contact",
      "Generate from WiFi credentials", "History of generated codes"]),
    ("QR Scanner", "app.bardom.qrscan",
     "Scan QR codes and barcodes using the camera",
     ["Open camera preview", "Detect QR code in real-time",
      "Decode barcode value", "Open URL in browser",
      "Copy to clipboard", "Scan history",
      "Flashlight toggle for scanning", "Vibrate on detection",
      "Save scanned image", "Share decoded text"]),
    ("Unit Converter", "app.bardom.units",
     "Convert between common units",
     ["Length: m/km/ft/mile", "Mass: kg/g/lb/oz",
      "Temperature: C/F/K", "Volume: L/mL/gal",
      "Speed: km/h/mph/m/s", "Area: m²/ft²/acre",
      "Pressure: Pa/bar/psi", "Energy: J/cal/kWh",
      "Time: s/min/h/day", "Save favorite conversions"]),

    # 11-20: social & communication
    ("Chat App", "app.bardom.chat",
     "A simple chat application",
     ["Display message list", "Send text message",
      "Receive message via polling", "Show timestamp per message",
      "Online/offline status", "Typing indicator",
      "Send image attachment", "Delete message",
      "Search messages", "Group chat support"]),
    ("Contacts", "app.bardom.contacts",
     "Manage contacts locally",
     ["Add new contact", "Edit contact",
      "Delete contact", "List all contacts alphabetically",
      "Search by name", "Search by phone number",
      "Add contact photo", "Import from phonebook",
      "Export as vCard", "Mark as favorite"]),
    ("Email Client", "app.bardom.email",
     "A minimal email reader",
     ["Inbox view", "Open and read email",
      "Compose new email", "Reply to email",
      "Forward email", "Delete email",
      "Mark as spam", "Move to folder",
      "Attach file", "Search emails"]),
    ("Walkie Talkie", "app.bardom.walkie",
     "Push-to-talk voice communication over WiFi",
     ["Push to talk button", "Record audio",
      "Send audio over UDP", "Receive audio and play",
      "Connect to room by IP", "Volume control",
      "Show speaking indicator", "Mute microphone",
      "Voice activation mode", "Save transmission log"]),
    ("Forum Reader", "app.bardom.forum",
     "Read a public forum feed",
     ["List of latest topics", "Open topic detail",
      "Read comments", "Post a new comment",
      "Upvote a topic", "Bookmark a topic",
      "Dark mode", "Search topics",
      "Filter by category", "Share topic link"]),
    ("RSS Reader", "app.bardom.rss",
     "Subscribe to RSS feeds",
     ["Add RSS feed URL", "List articles from feed",
      "Open article in browser", "Mark as read",
      "Mark as favorite", "Refresh feeds",
      "Delete feed", "Search articles",
      "Offline reading cache", "Notification on new article"]),
    ("Social Feed", "app.bardom.feed",
     "A social media feed reader",
     ["Display feed posts", "Like a post",
      "Comment on post", "Share post",
      "Follow user", "Unfollow user",
      "Profile page", "Search users",
      "Notifications", "Dark mode"]),
    ("Messenger", "app.bardom.msg",
     "Instant messaging with notifications",
     ["Send message", "Receive message",
      "Push notification", "Message status: sent/delivered/read",
      "Media attachments", "Voice messages",
      "Group messaging", "Block user",
      "Mute conversation", "Archive conversation"]),
    ("Blog Reader", "app.bardom.blog",
     "Read blog posts from a feed",
     ["List latest posts", "Open post detail",
      "Read full content", "Share post",
      "Bookmark post", "Dark mode",
      "Search posts", "Filter by tag",
      "Author profile", "Comment section"]),
    ("Podcast Player", "app.bardom.podcast",
     "Subscribe to and play podcasts",
     ["Browse podcast directory", "Subscribe to podcast",
      "List episodes", "Play episode",
      "Download for offline", "Show playback speed",
      "Skip 30 seconds", "Sleep timer",
      "Show notes", "Mark as played"]),

    # 21-30: media
    ("Music Player", "app.bardom.music",
     "Play local music files",
     ["List songs on device", "Play selected song",
      "Pause/playback", "Next/previous track",
      "Shuffle mode", "Repeat mode",
      "Show progress bar", "Seek to position",
      "Create playlist", "Show album art"]),
    ("Video Player", "app.bardom.video",
     "Play video files",
     ["List videos on device", "Play selected video",
      "Show playback controls", "Seek bar",
      "Adjust volume", "Change aspect ratio",
      "Subtitle support", "Picture-in-picture",
      "Screenshot", "Loop playback"]),
    ("Camera", "app.bardom.camera",
     "Take photos with the camera",
     ["Open camera preview", "Capture photo",
      "Switch front/back camera", "Flash toggle",
      "Timer 3/10 seconds", "Grid overlay",
      "Save to gallery", "Apply filter",
      "Burst mode", "Record video"]),
    ("Photo Editor", "app.bardom.photoedit",
     "Edit photos with filters and adjustments",
     ["Load photo from gallery", "Crop photo",
      "Rotate photo", "Adjust brightness",
      "Adjust contrast", "Apply filter",
      "Add text overlay", "Save edited photo",
      "Undo changes", "Share edited photo"]),
    ("Audio Recorder", "app.bardom.recorder",
     "Record audio from microphone",
     ["Start recording", "Pause recording",
      "Stop and save", "List recordings",
      "Play recording", "Rename recording",
      "Delete recording", "Share recording",
      "Recording format selector", "Show waveform"]),
    ("Gallery", "app.bardom.gallery",
     "Browse photos and videos",
     ["Grid of thumbnails", "Open full screen",
      "Swipe between items", "Pinch to zoom",
      "Share item", "Delete item",
      "Show details", "Filter by type",
      "Slideshow mode", "Multi-select"]),
    ("Radio Player", "app.bardom.radio",
     "Stream internet radio stations",
     ["List of stations", "Play station",
      "Pause stream", "Volume control",
      "Favorite stations", "Search stations",
      "Now playing info", "Sleep timer",
      "Record stream", "Share station"]),
    ("Soundboard", "app.bardom.soundboard",
     "Play sound effects on tap",
     ["Grid of sound buttons", "Play sound on tap",
      "Long-press to set as ringtone", "Categories tab",
      "Search sounds", "Favorite sounds",
      "Volume slider", "Loop mode",
      "Stop all sounds", "Custom sound upload"]),
    ("Lyrics Viewer", "app.bardom.lyrics",
     "Show lyrics for currently playing song",
     ["Search by song name", "Search by artist",
      "Show synced lyrics", "Save lyrics offline",
      "Edit lyrics", "Share lyrics",
      "Dark mode", "Font size adjust",
      "Highlight current line", "Translate lyrics"]),
    ("Metronome", "app.bardom.metronome",
     "A musical metronome",
     ["Set BPM", "Start/stop metronome",
      "Time signature 2/4/3/4/4/4", "Visual indicator",
      "Vibrate on beat", "Tap to set BPM",
      "Save presets", "Subdivisions",
      "Accent first beat", "Background mode"]),

    # 31-40: productivity
    ("Calendar", "app.bardom.calendar",
     "A monthly calendar with events",
     ["Show month view", "Add event on date",
      "Edit event", "Delete event",
      "Event reminder notification", "List upcoming events",
      "Weekly view", "Daily view",
      "Search events", "Export to ICS"]),
    ("File Manager", "app.bardom.files",
     "Browse and manage files on device",
     ["List directory contents", "Open file",
      "Copy file", "Move file",
      "Delete file", "Rename file",
      "Create folder", "Search files",
      "Sort by name/size/date", "Show storage info"]),
    ("PDF Reader", "app.bardom.pdf",
     "Open and read PDF files",
     ["Open PDF from storage", "Page navigation",
      "Zoom in/out", "Search text in PDF",
      "Bookmark page", "Jump to page",
      "Night mode", "Thumbnail view",
      "Highlight text", "Share PDF"]),
    ("Document Scanner", "app.bardom.docscan",
     "Scan documents with the camera",
     ["Capture document photo", "Auto-detect edges",
      "Crop and perspective correct", "Convert to grayscale",
      "Enhance contrast", "Save as PDF",
      "Multi-page documents", "OCR text extraction",
      "Share scanned PDF", "Organize by folder"]),
    ("Cloud Drive", "app.bardom.cloud",
     "Browse cloud-stored files",
     ["Login with token", "List remote files",
      "Download file", "Upload file",
      "Create folder", "Delete remote file",
      "Share link", "Search files",
      "Sync status", "Offline cache"]),
    ("Markdown Editor", "app.bardom.markdown",
     "Edit Markdown files with live preview",
     ["Edit markdown text", "Live HTML preview",
      "Save .md file", "Open existing .md",
      "Export as HTML", "Syntax highlighting",
      "Dark mode", "Word count",
      "Search and replace", "Recent files list"]),
    ("Password Manager", "app.bardom.pwdmgr",
     "Store passwords encrypted",
     ["Master password login", "Add credential entry",
      "Edit entry", "Delete entry",
      "Search entries", "Generate strong password",
      "Copy to clipboard", "Auto-lock after 5 min",
      "Backup encrypted database", "Biometric unlock"]),
    ("Habit Tracker", "app.bardom.habits",
     "Track daily habits",
     ["Add new habit", "Mark habit done today",
      "Streak counter", "Weekly view",
      "Monthly view", "Statistics chart",
      "Reminder notifications", "Edit habit",
      "Archive habit", "Export data as CSV"]),
    ("Expense Tracker", "app.bardom.expense",
     "Track personal expenses",
     ["Add expense entry", "Categorize expense",
      "Edit entry", "Delete entry",
      "Monthly summary", "Category breakdown chart",
      "Budget limit alert", "Export as CSV",
      "Search entries", "Recurring expenses"]),
    ("Weather", "app.bardom.weather",
     "Show current weather and forecast",
     ["Show current temperature", "Show humidity and wind",
      "5-day forecast", "Hourly forecast",
      "Search by city", "Use current location",
      "Weather alerts", "Sunrise/sunset times",
      "Refresh data", "Switch units C/F"]),

    # 41-50: education
    ("Flashcards", "app.bardom.flashcards",
     "Study with flashcards",
     ["Create deck of cards", "Add card to deck",
      "Edit card", "Delete card",
      "Study mode", "Shuffle deck",
      "Mark card as known", "Progress tracking",
      "Import from CSV", "Export deck"]),
    ("Dictionary", "app.bardom.dict",
     "Look up word definitions",
     ["Search word", "Show definition",
      "Show pronunciation", "Show example sentences",
      "Add to favorites", "Search history",
      "Word of the day", "Offline mode",
      "Synonyms and antonyms", "Share definition"]),
    ("Quiz App", "app.bardom.quiz",
     "Take multiple-choice quizzes",
     ["Start quiz", "Show question with options",
      "Select answer", "Show correct answer",
      "Next question", "Final score",
      "Review wrong answers", "Timer per question",
      "Category selection", "High score tracking"]),
    ("Language Learner", "app.bardom.lang",
     "Learn a new language",
     ["Daily lesson", "Vocabulary list",
      "Practice with flashcards", "Listen to pronunciation",
      "Speak and check", "Grammar tips",
      "Progress tracking", "Streak counter",
      "Review weak words", "Leaderboard"]),
    ("Math Trainer", "app.bardom.mathtrain",
     "Practice mental math",
     ["Generate random problem", "Enter answer",
      "Check answer", "Show correct solution",
      "Difficulty levels", "Timer",
      "Score tracking", "Streak counter",
      "Operation selector + - × ÷", "Statistics"]),
    ("Periodic Table", "app.bardom.chem",
     "Interactive periodic table",
     ["Show periodic table grid", "Tap element for details",
      "Atomic mass display", "Electron configuration",
      "Search by symbol", "Filter by category",
      "Element properties", "Bohr model view",
      "Quiz mode", "Favorites"]),
    ("World Map", "app.bardom.map",
     "Browse an interactive world map",
     ["Show world map", "Tap country for info",
      "Search country", "Show capital city",
      "Show flag", "Show population",
      "Show area", "Show currency",
      "Quiz mode", "Favorites"]),
    ("Spelling Bee", "app.bardom.spell",
     "Practice spelling words",
     ["Listen to word", "Type the word",
      "Check spelling", "Show correct spelling",
      "Difficulty levels", "Hint button",
      "Word definition", "Statistics",
      "Practice mode", "Test mode"]),
    ("Geography Quiz", "app.bardom.geoquiz",
     "Test geography knowledge",
     ["Capital city questions", "Flag identification",
      "Continent questions", "River and mountain questions",
      "Score tracking", "Timer per question",
      "Difficulty levels", "Review wrong answers",
      "Category selector", "High score"]),
    ("Typing Tutor", "app.bardom.typing",
     "Improve typing speed",
     ["Show text to type", "Track WPM",
      "Track accuracy", "Show errors",
      "Difficulty levels", "Practice lessons",
      "Custom text", "Progress chart",
      "Timed test", "High score"]),

    # 51-60: games
    ("Tic-Tac-Toe", "app.bardom.tictactoe",
     "Classic tic-tac-toe game",
     ["3x3 grid UI", "Two-player mode",
      "Single-player vs AI", "Detect winner",
      "Detect draw", "Reset board",
      "Score tracking", "Sound effects",
      "Choose symbol X/O", "AI difficulty"]),
    ("Memory Match", "app.bardom.memory",
     "Card matching memory game",
     ["4x4 grid of cards", "Flip card on tap",
      "Match pairs", "Hide unmatched cards",
      "Move counter", "Timer",
      "Win detection", "Difficulty levels",
      "Sound effects", "High score"]),
    ("Snake Game", "app.bardom.snake",
     "Classic snake game",
     ["Snake movement", "Food generation",
      "Grow on eat", "Game over on collision",
      "Score display", "High score",
      "Swipe controls", "Pause/resume",
      "Speed increase", "Sound effects"]),
    ("2048", "app.bardom.game2048",
     "Slide and merge number tiles",
     ["4x4 grid of tiles", "Swipe to move",
      "Merge equal tiles", "Spawn new tile",
      "Score counter", "Best score",
      "Game over detection", "Win at 2048",
      "Continue after win", "Undo move"]),
    ("Sudoku", "app.bardom.sudoku",
     "9x9 Sudoku puzzle",
     ["Generate puzzle", "Input number per cell",
      "Validate solution", "Hint button",
      "Difficulty levels", "Timer",
      "Pencil marks", "Check progress",
      "Reset puzzle", "New puzzle"]),
    ("Minesweeper", "app.bardom.mines",
     "Classic minesweeper",
     ["8x8 grid", "Tap to reveal",
      "Long-press to flag", "Number of adjacent mines",
      "Win/lose detection", "Timer",
      "Mine counter", "Reset game",
      "Difficulty levels", "First-tap safe"]),
    ("Pong", "app.bardom.pong",
     "Two-paddle Pong game",
     ["Two paddles", "Ball physics",
      "Score tracking", "Win at 11 points",
      "Touch controls", "AI opponent",
      "Sound effects", "Pause/resume",
      "Speed increase", "Reset game"]),
    ("Brick Breaker", "app.bardom.breakout",
     "Breakout-style brick game",
     ["Paddle control", "Ball physics",
      "Brick layout", "Brick destruction",
      "Lives counter", "Score tracking",
      "Level progression", "Sound effects",
      "Pause/resume", "Game over"]),
    ("Word Search", "app.bardom.wordsearch",
     "Find hidden words in a grid",
     ["10x10 letter grid", "Word list display",
      "Drag to select", "Validate selection",
      "Mark found words", "Timer",
      "Difficulty levels", "Hint button",
      "Category themes", "Reset puzzle"]),
    ("Hangman", "app.bardom.hangman",
     "Classic word-guessing game",
     ["Random word selection", "Display blanks",
      "Letter input", "Wrong guess counter",
      "Hangman drawing", "Win/lose detection",
      "Hint button", "Category selection",
      "Score tracking", "New game"]),

    # 61-70: health & fitness
    ("Step Counter", "app.bardom.steps",
     "Count daily steps using accelerometer",
     ["Count steps via sensor", "Daily goal progress",
      "Weekly chart", "Calories estimate",
      "Distance estimate", "Start/pause tracking",
      "Reset counter", "Notification with progress",
      "History by day", "Export as CSV"]),
    ("Water Reminder", "app.bardom.water",
     "Remind user to drink water",
     ["Daily goal setting", "Log water intake",
      "Reminder notifications", "Progress visualization",
      "Custom cup size", "History by day",
      "Streak counter", "Achievement badges",
      "Adjustable reminder interval", "Export history"]),
    ("Heart Rate Monitor", "app.bardom.heartrate",
     "Measure heart rate using camera",
     ["Place finger on camera", "Detect pulse via color change",
      "Calculate BPM", "Show graph",
      "Save measurement", "History list",
      "Resting/exercise zones", "Average heart rate",
      "Export data", "Share result"]),
    ("Meditation Timer", "app.bardom.meditate",
     "Guided meditation timer",
     ["Set session duration", "Start/pause timer",
      "Ambient sound option", "Interval bell",
      "Daily reminder", "Streak counter",
      "Pre-set sessions 5/10/15/20 min", "Background mode",
      "Statistics", "Custom interval"]),
    ("Sleep Tracker", "app.bardom.sleep",
     "Track sleep patterns",
     ["Set bedtime", "Set wake time",
      "Track sleep duration", "Sleep quality rating",
      "Weekly chart", "Wake-up alarm",
      "Sleep sounds", "Dream journal",
      "Smart wake window", "Export data"]),
    ("Workout Tracker", "app.bardom.workout",
     "Log workouts and exercises",
     ["Add workout session", "List exercises",
      "Set reps and sets", "Track weight lifted",
      "Rest timer", "Workout history",
      "Personal records", "Body weight tracker",
      "Statistics", "Export as CSV"]),
    ("Calorie Counter", "app.bardom.calories",
     "Track daily calorie intake",
     ["Search food database", "Add food to log",
      "Calculate total calories", "Daily goal progress",
      "Macronutrient breakdown", "Water tracking",
      "Exercise calorie burn", "Weekly summary",
      "Custom food entry", "Barcode scan"]),
    ("Yoga Guide", "app.bardom.yoga",
     "Guided yoga sessions",
     ["List of poses", "Pose image and description",
      "Session builder", "Timer per pose",
      "Difficulty levels", "Progress tracking",
      "Favorite poses", "Custom sessions",
      "Reminder notification", "Statistics"]),
    ("Cycle Tracker", "app.bardom.cycle",
     "Track menstrual cycle",
     ["Log cycle start", "Predict next cycle",
      "Symptom tracking", "Mood tracking",
      "Fertility window", "Reminder notification",
      "Cycle history", "Statistics",
      "Notes per day", "Export data"]),
    ("BMI Calculator", "app.bardom.bmi",
     "Calculate Body Mass Index",
     ["Input height", "Input weight",
      "Calculate BMI", "Show category",
      "Metric/imperial toggle", "Save measurements",
      "History chart", "Ideal weight range",
      "Tips per category", "Share result"]),

    # 71-80: travel & location
    ("Maps Browser", "app.bardom.maps",
     "Open StreetMap-based map viewer",
     ["Show world map", "Search location",
      "Drop pin", "Get directions",
      "Show current location", "Save favorite places",
      "Measure distance", "Offline cache",
      "Map style toggle", "Share location"]),
    ("Compass Plus", "app.bardom.compass2",
     "Advanced compass with GPS",
     ["Show heading", "Show coordinates",
      "Show altitude", "Show speed",
      "Mark waypoint", "Navigate to waypoint",
      "Sun position", "Moon phase",
      "Tide times", "Share position"]),
    ("Translator", "app.bardom.translate",
     "Translate text between languages",
     ["Select source language", "Select target language",
      "Input text", "Show translation",
      "Voice input", "Voice output",
      "Copy translation", "History",
      "Favorite translations", "Offline dictionary"]),
    ("Currency Converter", "app.bardom.currency",
     "Convert between currencies",
     ["Select source currency", "Select target currency",
      "Enter amount", "Show converted amount",
      "Live exchange rates", "Historical chart",
      "Favorite pairs", "Multi-currency view",
      "Offline last-known rates", "Calculator mode"]),
    ("Travel Planner", "app.bardom.travel",
     "Plan trips and itineraries",
     ["Create new trip", "Add destination",
      "Add activity", "Set dates",
      "Budget tracker", "Packing list",
      "Map view of itinerary", "Share trip",
      "Backup to cloud", "Export as PDF"]),
    ("Speedometer", "app.bardom.speed",
     "Show current speed using GPS",
     ["Show current speed", "Show max speed",
      "Show average speed", "Speed unit km/h or mph",
      "Speed alert", "Trip distance",
      "Trip timer", "HUD mode",
      "Background tracking", "Export trip data"]),
    ("Altimeter", "app.bardom.altitude",
     "Show current altitude",
     ["Show altitude via GPS", "Show barometric altitude",
      "Show sea level pressure", "Record altitude profile",
      "Show chart", "Save waypoints",
      "Calibrate to known altitude", "Share reading",
      "History log", "Export data"]),
    ("Parking Reminder", "app.bardom.parking",
     "Remember where you parked",
     ["Save current location", "Take parking photo",
      "Set parking timer", "Navigate back to car",
      "Notes field", "Share location",
      "Parking history", "Floor/level field",
      "Notification when timer expires", "Multiple vehicles"]),
    ("Hiking Tracker", "app.bardom.hiking",
     "Track hiking routes",
     ["Start hike", "Record GPS track",
      "Show distance", "Show elevation gain",
      "Show duration", "Pause/resume",
      "Save hike", "View past hikes",
      "Export as GPX", "Statistics"]),
    ("Geocaching", "app.bardom.geo",
     "Geocaching treasure hunt",
     ["List nearby caches", "Show cache on map",
      "Navigate to cache", "Log find",
      "Add description", "Take photo at cache",
      "Save offline", "Trackable items",
      "Difficulty rating", "Share find"]),

    # 81-90: smart home & IoT
    ("Smart Home", "app.bardom.smarthome",
     "Control smart home devices",
     ["List devices", "Toggle device on/off",
      "Adjust brightness", "Set color",
      "Group devices by room", "Schedule on/off",
      "Scene presets", "Voice control",
      "Energy usage", "Notifications"]),
    ("Plant Monitor", "app.bardom.plants",
     "Track plant care schedule",
     ["Add plant", "Set watering schedule",
      "Set fertilizing schedule", "Photo log",
      "Notes per plant", "Reminder notifications",
      "Plant database", "Care tips",
      "Statistics", "Export data"]),
    ("Thermostat", "app.bardom.thermo",
     "Control home thermostat",
     ["Show current temperature", "Set target temperature",
      "Schedule program", "Mode heat/cool/auto",
      "Energy report", "Away mode",
      "Fan control", "Humidity display",
      "Multiple zones", "Notifications"]),
    ("Doorbell", "app.bardom.doorbell",
     "Smart doorbell viewer",
     ["Live video feed", "Two-way audio",
      "Motion detection alert", "Snapshot",
      "Record video", "Night vision toggle",
      "Doorbell history", "Silent mode",
      "Custom ringtone", "Multi-camera"]),
    ("Robot Vacuum", "app.bardom.vacuum",
     "Control robot vacuum",
     ["Start cleaning", "Stop and dock",
      "Schedule cleaning", "Map view",
      "Zone cleaning", "Battery status",
      "Cleaning history", "Filter replacement alert",
      "Spot cleaning", "Quiet mode"]),
    ("Lighting Control", "app.bardom.lights",
     "Control smart lights",
     ["List lights", "Toggle on/off",
      "Brightness slider", "Color picker",
      "Scene presets", "Schedules",
      "Group control", "Music sync",
      "Wake-up routine", "Sunset routine"]),
    ("Sprinkler", "app.bardom.sprinkler",
     "Control garden sprinklers",
     ["List zones", "Start zone manually",
      "Schedule watering", "Rain skip",
      "Water usage report", "Pause all",
      "Zone runtime", "Weather integration",
      "Notifications", "Multiple programs"]),
    ("Garage Door", "app.bardom.garage",
     "Control garage door opener",
     ["Show door status", "Open/close toggle",
      "Schedule close", "Notification on movement",
      "Multiple doors", "Share access",
      "Activity log", "Geo-fence auto-open",
      "Pin code access", "Camera view"]),
    ("Pet Feeder", "app.bardom.feeder",
     "Control automatic pet feeder",
     ["Feed now button", "Set feeding schedule",
      "Portion size", "Food level indicator",
      "Feeding history", "Photo of pet",
      "Voice message playback", "Multiple pets",
      "Low food alert", "Manual override"]),
    ("Air Quality", "app.bardom.air",
     "Monitor air quality sensors",
     ["Show PM2.5 reading", "Show CO2 reading",
      "Show humidity", "Show temperature",
      "Historical chart", "Alert thresholds",
      "Recommendations", "Multiple rooms",
      "Export data", "Notification on high pollution"]),

    # 91-100: finance & misc
    ("Tip Calculator", "app.bardom.tip",
     "Calculate tip and split bill",
     ["Enter bill amount", "Set tip percentage",
      "Split between people", "Round up option",
      "Custom tip percentage", "Save calculation",
      "Currency selector", "Tax separate",
      "History", "Share result"]),
    ("Stock Tracker", "app.bardom.stocks",
     "Track stock prices",
     ["Search ticker", "Add to watchlist",
      "Show current price", "Show daily change",
      "Historical chart", "Set price alert",
      "Portfolio view", "News feed",
      "Multiple exchanges", "Export data"]),
    ("Budget Planner", "app.bardom.budget",
     "Plan monthly budget",
     ["Set income", "Add expense categories",
      "Set budget per category", "Track spending",
      "Show remaining budget", "Alert on overspend",
      "Monthly summary", "Yearly chart",
      "Savings goals", "Export as CSV"]),
    ("Loan Calculator", "app.bardom.loan",
     "Calculate loan payments",
     ["Enter loan amount", "Enter interest rate",
      "Enter term in months", "Calculate monthly payment",
      "Show total interest", "Show amortization schedule",
      "Compare loans", "Extra payment option",
      "Save calculation", "Share result"]),
    ("Invoice Maker", "app.bardom.invoice",
     "Create and send invoices",
     ["Add client", "Add line items",
      "Set tax rate", "Generate PDF",
      "Send via email", "Track payment status",
      "Invoice history", "Recurring invoices",
      "Custom branding", "Export as CSV"]),
    ("Crypto Tracker", "app.bardom.crypto",
     "Track cryptocurrency prices",
     ["List of top coins", "Search by name",
      "Show price chart", "Set price alert",
      "Portfolio tracker", "Add transaction",
      "Profit/loss calculation", "News feed",
      "Multiple currencies", "Export data"]),
    ("Receipt Scanner", "app.bardom.receipts",
     "Scan and organize receipts",
     ["Capture receipt photo", "OCR text extraction",
      "Extract amount and date", "Categorize",
      "Search receipts", "Export as CSV",
      "Multiple currencies", "Tag for tax",
      "Cloud backup", "Statistics"]),
    ("Bill Splitter", "app.bardom.billsplit",
     "Split bills among friends",
     ["Add participants", "Add expense",
      "Assign payer", "Assign participants per expense",
      "Calculate who owes whom", "Settle up tracker",
      "Multiple events", "Export settlement plan",
      "Currency support", "Photo of receipt"]),
    ("Donation Tracker", "app.bardom.donate",
     "Track charitable donations",
     ["Add donation entry", "Categorize by charity",
      "Receipt photo", "Tax-deductible flag",
      "Annual summary", "Statistics by category",
      "Reminder for recurring", "Export for taxes",
      "Multiple payment methods", "Share impact"]),
    ("Tax Estimator", "app.bardom.tax",
     "Estimate annual taxes",
     ["Enter income", "Enter deductions",
      "Select filing status", "Calculate estimated tax",
      "Show tax bracket breakdown", "Compare scenarios",
      "Save calculation", "Refund estimator",
      "Quarterly payment reminder", "Export report"]),
]


def main() -> None:
    out_dir = Path(__file__).resolve().parent
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"Generating {len(TEMPLATES)} templates into {out_dir}")
    for idx, (name, pkg, desc, features) in enumerate(TEMPLATES, start=1):
        tmpl = {
            "id": f"template_{idx:03d}",
            "name": name,
            "package": pkg,
            "version": "1.0.0",
            "min_sdk": 21,
            "target_sdk": 34,
            "description": desc,
            "features": features,
        }
        slug = name.lower().replace(" ", "_")
        out_path = out_dir / f"template_{idx:03d}_{slug}.json"
        out_path.write_text(json.dumps(tmpl, indent=2, ensure_ascii=False),
                            encoding="utf-8")
    print(f"Done. {len(list(out_dir.glob('template_*.json')))} templates written.")


if __name__ == "__main__":
    main()
